---
name: test

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: go test
    permissions: write-all
    runs-on: ubuntu-26.04
    steps:
      - name: Install dependencies
        run: |
          apt install -y curl
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Testing
        run: |
          env | sort
          cat /etc/os-release
